spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:5432/knowledge_db
    username: postgres
    password: root

logging:
  level:
    root: INFO
    com.enterprise.platform: DEBUG
    org.springframework.security: DEBUG
